### ISSUE TITLE
external_id_emitter: Emit reflected model data

### ISSUE THREAD

**Issue by naglis** [naglis/odd#58]
https://github.com/odoo/odoo/blob/514f782a76cc731b05506774cb39385455b241b6/odoo/models.py#L312-L316

- [x] [`ir.model`](https://github.com/odoo/odoo/blob/514f782a76cc731b05506774cb39385455b241b6/odoo/addons/base/models/ir_model.py#L267-L286) #85 
- [x] [`ir.model.fields`](https://github.com/odoo/odoo/blob/514f782a76cc731b05506774cb39385455b241b6/odoo/addons/base/models/ir_model.py#L866-L870) #91 
- [x] [`ir.model.fields.selection`](https://github.com/odoo/odoo/blob/514f782a76cc731b05506774cb39385455b241b6/odoo/addons/base/models/ir_model.py#L989-L1024) [v13+] #92
- [x] [`ir.model.constraint`](https://github.com/odoo/odoo/blob/514f782a76cc731b05506774cb39385455b241b6/odoo/addons/base/models/ir_model.py#L1279-L1288) #93
